# Generated by Django 2.1.1 on 2018-10-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
    ]
